name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-northeast-1 | \
          docker login --username AWS --password-stdin 638389535083.dkr.ecr.ap-northeast-1.amazonaws.com

      - name: Build API image
        run: |
          docker build --platform=linux/amd64 -t api:${{ github.sha }} ./api
          docker tag api:${{ github.sha }} 638389535083.dkr.ecr.ap-northeast-1.amazonaws.com/api:${{ github.sha }}

      - name: Create frontend env file
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> web/fe/.env.production

      - name: Build Frontend image
        run: |
          docker build --platform=linux/amd64 -t frontend:${{ github.sha }} ./web
          docker tag frontend:${{ github.sha }} 638389535083.dkr.ecr.ap-northeast-1.amazonaws.com/frontend:${{ github.sha }}

      - name: Push images
        run: | 
          docker push 638389535083.dkr.ecr.ap-northeast-1.amazonaws.com/api:${{ github.sha }}
          docker push 638389535083.dkr.ecr.ap-northeast-1.amazonaws.com/frontend:${{ github.sha }}

